config/routes.rb
Rails.application.routes.draw do
  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  namespace :potepan do
    get '/',                        to: 'products#index'
    get 'index',                    to: 'products#index'
    get :product_list_left_sidebar, to: 'sample#product_list_left_sidebar'
    get :cart_page,                 to: 'sample#cart_page'
    get :checkout_step_1,           to: 'sample#checkout_step_1'
    get :checkout_step_2,           to: 'sample#checkout_step_2'
    get :checkout_step_3,           to: 'sample#checkout_step_3'
    get :checkout_complete,         to: 'sample#checkout_complete'
    get :blog_left_sidebar,         to: 'sample#blog_left_sidebar'
    get :blog_right_sidebar,        to: 'sample#blog_right_sidebar'
    get :blog_single_left_sidebar,  to: 'sample#blog_single_left_sidebar'
    get :blog_single_right_sidebar, to: 'sample#blog_single_right_sidebar'
    get :about_us,                  to: 'sample#about_us'
    get :tokushoho,                 to: 'sample#tokushoho'
    get :privacy_policy,            to: 'sample#privacy_policy'
    resources :products, only: [:index, :show, :search] do
      collection do
        get :search
      end
    end
    resources :categories, only: [:show, :color, :size, :sort] do
      member do
        get :color
        get :size
        get :sort
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/option_value_decorator.rb
Spree::OptionValue.class_eval do
  scope :presentation, -> (presentation) {
    includes(:option_type).
      where(spree_option_types: { presentation: presentation }).
      uniq
  }
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  scope :with_price_and_images, -> {
    includes(master: [:default_price, :images])
  }
  scope :without_myself, -> (product) {
    where.not(id: product.id)
  }
  scope :related_products, -> (product, max) {
    in_taxons(product.taxons).distinct.sample(max)
  }
  scope :descend_by_available, -> {
    order(available_on: "DESC")
  }
  scope :ascend_by_available, -> {
    order(available_on: "ASC")
  }
  scope :select_by_category, -> (taxon) {
    taxon.all_products.with_price_and_images
  }
  scope :filter_by_color, -> (color) {
    joins(variants_including_master: :option_values).
      includes(variants_including_master: :option_values).
      where("spree_option_values.presentation = ?", color)
  }
  scope :filter_by_size, -> (size) {
    joins(variants_including_master: :option_values).
      includes(variants_including_master: :option_values).
      where("spree_option_values.presentation = ?", size)
  }
  scope :sort_by_order, -> (standard) {
    case standard
    when "ascend_by_price"
      ascend_by_master_price
    when "descend_by_price"
      descend_by_master_price
    when "descend_by_available"
      descend_by_available
    when "ascend_by_available"
      ascend_by_available
    end
  }

  scope :search_name_or_description, -> (search_word) {
    where(['name LIKE ? OR description LIKE ?', "%#{sanitize_sql_like(search_word)}%", 
      "%#{sanitize_sql_like(search_word)}%"]) if search_word.present?
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/potepan/categories_controller.rb
class Potepan::CategoriesController < ApplicationController
  helper_method :count_number_of_products
  before_action :setup_values

  def setup_values
    @taxonomies = Spree::Taxonomy.all
    @taxon = Spree::Taxon.find(params[:id])
    @colors = Spree::OptionValue.presentation("Color")
    @sizes = Spree::OptionValue.presentation("Size")
  end

  def show
    @products = Spree::Product.select_by_category(@taxon)
  end

  def color
    @products = Spree::Product.
      select_by_category(@taxon).
      filter_by_color(params[:color])
    render 'potepan/categories/show'
  end

  def size
    @products = Spree::Product.
      select_by_category(@taxon).
      filter_by_size(params[:size])
    render 'potepan/categories/show'
  end

  def sort
    @products = Spree::Product.
      select_by_category(@taxon).
      sort_by_order(params[:sort])
    render 'potepan/categories/show'
  end

  private

  def count_number_of_products(option_value)
    Spree::Product.
      includes(variants: :option_values).
      in_taxon(@taxon).
      where(spree_option_values: { name: option_value }).
      count
  end
end

app/controllers/potepan/products_controller.rb
class Potepan::ProductsController < ApplicationController
  def index
    @products_new = Spree::Product.
      with_price_and_images.
      descend_by_available.
      limit(5)
  end

  def show
    @product = Spree::Product.find(params[:id])
    @related_products = Spree::Product.
      with_price_and_images.
      without_myself(@product).
      related_products(@product, 4)
  end

  def search
    @search_word = params[:search]
    @products = Spree::Product.
      with_price_and_images.
      search_name_or_description(@search_word)
  end
end

app/controllers/potepan/sample_controller.rb
class Potepan::SampleController < ApplicationController
  def index
  end

  def product_grid_left_sidebar
  end

  def product_list_left_sidebar
  end

  def single_product
  end

  def cart_page
  end

  def checkout_step_1
  end

  def checkout_step_2
  end

  def checkout_step_3
  end

  def checkout_complete
  end

  def blog_left_sidebar
  end

  def blog_right_sidebar
  end

  def blog_single_left_sidebar
  end

  def blog_single_right_sidebar
  end

  def about_us
  end

  def tokushoho
  end

  def privacy_policy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "BIG BAG"
    if page_title.blank?
      "#{base_title}"
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/views/layouts/_footer.html.erb
<!-- COPY RIGHT -->
<div id="footer" class="copyRight clearfix">
  <div class="container">
    <div class="row">
      <div class="col-sm-7 col-xs-12">
        <p>&copy; 2016-<%= Time.current.year %> Copyright Potepan Store .</p>
      </div>
      <div class="col-sm-5 col-xs-12">
        <ul class="list-inline">
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_head.html.erb
<!-- SITE TITTLE -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><%= full_title(yield(:title)) %></title>

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all' %>

<!-- PLUGINS CSS STYLE -->

<!-- GOOGLE FONT -->
<%= stylesheet_link_tag "application", 'https://fonts.googleapis.com/css?family=Oxygen:400,300,700', :media => "all" %>

<!-- CUSTOM CSS -->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

app/views/layouts/_header.html.erb
<div class="header clearfix">
  <div class="topBar">
    <div class="container">
      <div class="row">
        <div class="col-md-6 hidden-sm hidden-xs">
          <ul class="list-inline">
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          </ul>
        </div>
        <div class="col-md-6 col-xs-12">
          <ul class="list-inline pull-right">
            <li class="dropdown searchBox">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-search"></i></a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li>
                  <%= form_tag(search_potepan_products_path, id: "form01", method: "get", enforce_utf8: false) do %>
                    <span class="input-group">
                    <%= text_field_tag :search, "", class: "form-control", placeholder: "Search…", aria_describedby: "basic-addon2" %>
                    <button><span class="input-group-addon" id="basic-addon2" onclick="this.form.submit()">検索</span></button>
                  <% end %>
                  </span>
                </li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="cart-page.html" class="dropdown-toggle" data-toggle="dropdown disabled"><i class="fa fa-shopping-cart"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-main navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/potepan"><%= image_tag("img/logo.png", :alt => "") %></a>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/potepan">Home</a></li>
          <li class="dropdown megaDropMenu active">
            <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="300" data-close-others="true" aria-expanded="false">Shop</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/layouts/_login_modal.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">log in</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="login-email">Enter Email</label>
            <input type="email" class="form-control" id="login-email">
          </div>
          <div class="form-group">
            <label for="login-password">Password</label>
            <input type="password" class="form-control" id="login-password">
          </div>
          <div class="checkbox">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
          <button type="submit" class="btn btn-primary btn-block">log in</button>
          <button type="button" class="btn btn-link btn-block">Forgot Password?</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_product_quick_view_modal.html.erb
<div class="modal fade quick-view" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <div class="media">
          <div class="media-left">
            <%= image_tag("products/quick-view/quick-view-01.jpg", :class => "media-object", :alt => "Image") %>
          </div>
          <div class="media-body">
            <h2>Old Skool Navy</h2>
            <h3>149円</h3>
            <p>Classic sneaker from Vans. Cotton canvas and suede upper. Textile lining with heel stabilizer and ankle support. Contrasting laces. Sits on a classic waffle rubber sole.</p>
            <span class="quick-drop">
              <select name="guiest_id3" id="guiest_id3" class="select-drop">
                <option value="0">S</option>
                <option value="1">M</option>
                <option value="2">L</option>
                <option value="3">XL</option>
              </select>
            </span>
            <span class="quick-drop resizeWidth">
              <select name="guiest_id4" id="guiest_id4" class="select-drop">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
              </select>
            </span>
            <div class="btn-area">
              <a href="cart_page.html" class="btn btn-primary btn-block">カートへ入れる <i class="fa fa-angle-right" aria-hidden="true"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_signup_modal.html.erb
<div class="modal fade" id="signup" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Create an account</h3>
      </div>
      <div class="modal-body">
        <form action="" method="POST" role="form">
          <div class="form-group">
            <label for="signup-email">Enter Email</label>
            <input type="email" class="form-control" id="signup-email">
          </div>
          <div class="form-group">
            <label for="signup-password">Password</label>
            <input type="password" class="form-control" id="signup-password">
          </div>
          <div class="form-group">
            <label for="signup-password-confirmation">Confirm Password</label>
            <input type="password" class="form-control" id="signup-password-confirmation">
          </div>
          <button type="submit" class="btn btn-primary btn-block">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= render 'layouts/login_modal' %>
    <%= render 'layouts/signup_modal' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/potepan/categories/_filter_by_color.html.erb
<li>
  <%= link_to color_potepan_category_path(params[:id], color: color.presentation) do %>
    <%= color.presentation %><span><%= "(#{count_number_of_products(color.presentation)})" %></span>
  <% end %>
</li>

app/views/potepan/categories/_filter_by_size.html.erb
<li>
  <%= link_to size_potepan_category_path(params[:id], size: size.presentation) do %>
    <%= size.presentation %><span><%= "(#{count_number_of_products(size.name)})" %></span>
  <% end %>
</li>

app/views/potepan/categories/_light_section.html.erb
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= taxon.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="/potepan">Home</a>
          </li>
          <li>
            <a href="#">shop</a>
          </li>
          <li class="active"><%= taxon.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/categories/_products_under_taxon.html.erb
<div class="col-sm-4 col-xs-12">
  <div class="productBox">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url, :alt => "featured-product-img") %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= link_to product.name, potepan_product_path(product.id) %></h5>
      <h3><%= product.display_price %></h3>
    </div>
  </div>
</div>

app/views/potepan/categories/_taxonomies_sidebar.html.erb
<li>
  <a href="javascript:;" data-toggle="collapse" data-target="#<%= taxonomy.name %>"><%= taxonomy.name %><i class="fa fa-plus"></i></a>
  <ul id="<%= taxonomy.name %>" class="collapse collapseItem">
    <% taxonomy.taxons.leaves.each do |leaf| %>
     <li><%= link_to(content_tag(:i, "#{leaf.name} (#{leaf.products.size})", class: "fa fa-caret-right"), potepan_category_path(leaf.id)) %></li>
　　 <% end %>
  </ul>
</li>

app/views/potepan/categories/show.html.erb
<% provide(:title, @taxon.name) %>
<%= render 'light_section', taxon: @taxon %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-4 col-xs-12 sideBar">
        <div class="panel panel-default">
          <div class="panel-heading">商品カテゴリー</div>
          <div class="panel-body">
            <div class="collapse navbar-collapse navbar-ex1-collapse navbar-side-collapse">
              <ul class="nav navbar-nav side-nav">
                <%= render partial: 'taxonomies_sidebar', collection: @taxonomies, as: :taxonomy %>
              </ul>
            </div>
          </div>
        </div>
        <div class="panel panel-default filterNormal filter_by_color">
          <div class="panel-heading">色から探す</div>
          <div class="panel-body">
            <ul class="list-unstyled">
              <%= render partial: 'filter_by_color', collection: @colors, as: :color %>
            </ul>
          </div>
        </div>
        <div class="panel panel-default filterNormal filter_by_size">
          <div class="panel-heading">サイズから探す</div>
          <div class="panel-body">
            <ul class="list-unstyled clearfix">
              <%= render partial: 'filter_by_size', collection: @sizes, as: :size %>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-md-9 col-sm-8 col-xs-12">
        <div class="row filterArea">
          <div class="col-xs-6">
            <%= form_tag sort_potepan_category_path(@taxon.id), method: :get, enforce_utf8: false do %>
              <%= select_tag "sort", options_for_select([
                ["新着順", "descend_by_available"],
                ["安い順", "ascend_by_price"],
                ["高い順", "descend_by_price"],
                ["古い順", "ascend_by_available"]],
                selected: params[:sort] || "descend_by_available"),
                { class: "select-drop", onchange: "this.form.submit()"} %>
            <% end %>
          </div>
          <div class="col-xs-6">
            <div class="btn-group pull-right" role="group">
              <button type="button" class="btn btn-default active" onclick="window.location.href='product_grid_left_sidebar.html'"><i class="fa fa-th" aria-hidden="true"></i><span>Grid</span></button>
              <button type="button" class="btn btn-default" onclick="window.location.href='product_list_left_sidebar.html'"><i class="fa fa-th-list" aria-hidden="true"></i><span>List</span></button>
            </div>
          </div>
        </div>
        <div class="row">
          <%= render partial: 'products_under_taxon', collection: @products, as: :product %>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("img/home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_light_section.html.erb
<!-- LIGHT SECTION -->
<section class="lightSection clearfix pageHeader">
  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <div class="page-title">
          <h2><%= product.name %></h2>
        </div>
      </div>
      <div class="col-xs-6">
        <ol class="breadcrumb pull-right">
          <li>
            <a href="/potepan">Home</a>
          </li>
          <li class="active"><%= product.name %></li>
        </ol>
      </div>
    </div>
  </div>
</section>

app/views/potepan/products/_product_images_big.html.erb
<% product.images.each_with_index do |image, image_index| %>
  <% if image_index.zero? %>
    <div class="item active" data-thumb="<%= image_index %>">
      <%= image_tag(image.attachment.url) %>
    </div>
  <% else %>
    <div class="item" data-thumb="<%= image_index %>">
      <%= image_tag(image.attachment.url) %>
    </div>
  <% end %>
<% end %>

app/views/potepan/products/_product_images_small.html.erb
<% product.images.each_with_index do |image, image_index| %>
  <div data-target="#carousel" data-slide-to="<%= image_index %>" class="thumb">
    <%= image_tag(image.attachment.url(:small)) %>
  </div>
<% end %>

app/views/potepan/products/_products_new.html.erb
<%= link_to potepan_product_path(product.id) do %>
  <div class="slide">
    <div class="productImage clearfix">
      <%= image_tag(product.display_image.attachment.url, :alt => "featured-product-img") %>
    </div>
    <div class="productCaption clearfix">
      <h5><%= product.name %></h5>
      <h3><%= product.display_price %></h3>
    </div>
  </div>
<% end %>

app/views/potepan/products/_related_products.html.erb
<%= link_to potepan_product_path(product.id) do %>
  <div class="col-md-3 col-sm-6 col-xs-12">
    <div class="productBox">
      <div class="productImage clearfix">
        <%= image_tag(product.display_image.attachment.url, :alt => "products-img") %>
      </div>
      <div class="productCaption clearfix">
        <h5><%= product.name %></h5>
        <h3><%= product.display_price %></h3>
      </div>
    </div>
  </div>
<% end %>

app/views/potepan/products/index.html.erb
<% provide(:title, 'Top Page') %>
<!-- BANNER -->
<div class="bannercontainer">
  <div class="fullscreenbanner-container">
    <div class="fullscreenbanner">
      <ul>
        <li>
          <%= image_tag("home/banner-slider/slider-bg.jpg", :alt => "slidebg1", data:{bgposition: "center center", bgfit: "cover" , bgrepeat: "no-repeat"}) %>
        </li>
      </ul>
    </div>
  </div>
</div>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix">
  <div class="container">
    <div class="row featuredCollection">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>人気カテゴリー</h4>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='#';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-01.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Shirts ", potepan_category_path(6), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Shirts</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='#';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-02.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Bags", potepan_category_path(3), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Bags</h4>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-xs-12">
        <div class="thumbnail" onclick="location.href='#';">
          <div class="imageWrapper">
            <%= image_tag("home/featured-collection/featured-collection-03.jpg", :alt => "feature-collection-image") %>
            <div class="masking">
              <%= link_to "View Denim", potepan_category_path(5), class: "btn viewBtn" %>
            </div>
          </div>
          <div class="caption">
            <h4>Denim</h4>
          </div>
        </div>
      </div>
    </div>
    <div class="row featuredProducts">
      <div class="col-xs-12">
        <div class="page-header">
          <h4>新着商品</h4>
        </div>
      </div>
      <div class="col-xs-12">
        <div class="owl-carousel featuredProductsSlider">
          <%=  render partial: 'products_new', collection: @products_new, as: :product %>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- LIGHT SECTION -->
<section class="lightSection clearfix">
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <div class="owl-carousel partnersLogoSlider">
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-04.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-05.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-01.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-02.png", :alt => "partner-img") %>
            </div>
          </div>
          <div class="slide">
            <div class="partnersLogo clearfix">
              <%= image_tag("home/partners/partner-03.png", :alt => "partner-img") %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<%= render 'layouts/product_quick_view_modal' %>

      

app/views/potepan/products/search.html.erb
<% provide(:title, "#{@search_word}の検索結果") %>
<!-- MAIN CONTENT SECTION -->
<section class="mainContent clearfix productsContent">
  <div class="container">
    <div class="row">
      <div class="my-5 search-result">
        <h2><%= "『#{@search_word}』の検索結果: #{@products.count}件" %></h2>
      </div>
      <div class="col-md-8 col-sm-8 offset-md-2 col-xs-12">
        <div class="row">
          <%= render partial: 'potepan/categories/products_under_taxon', collection: @products, as: :product %>
        </div>
      </div>
    </div>
  </div>
</section>